### ISSUE TITLE
Incones do footer estao desproporsionais 

### ISSUE THREAD

**Issue by VictorHSCosta** [VictorHSCosta/Projeto-Final#13]
Eu fiz o footer mas nao consegui arrumar o simbolo do linkedim se alguem conseguirt arrumar eu ficarei grato 
![image](https://github.com/VictorHSCosta/Projeto-Final/assets/145876751/c51d057b-6034-4662-a256-8dbf4b2c36de)

**Comment by diogob003** [comment]
Header e o footer já estava prontos. Estão na branch [header-footer](/VictorHSCosta/Projeto-Final/tree/header-footer) e pull-request VictorHSCosta/Projeto-Final#11
