### ISSUE TITLE
Sobre

### ISSUE THREAD

**Issue by Pecximenes** [VictorHSCosta/Projeto-Final#6]
Criar o componente Sobre, seguindo a imagem:

![Screenshot from 2024-06-21 23-45-04](https://github.com/VictorHSCosta/Projeto-Final/assets/65309724/eff2d57c-08a7-46e5-9b3e-5bb84196698b)

**Comment by diogob003** [comment]
Fechando com 70c4c5f86d228d4ba114330e3896f0507423d72c

**Comment by diogob003** [comment]
Fechando com 70c4c5f86d228d4ba114330e3896f0507423d72c
