### ISSUE TITLE
Arquivo .env NÃO deve ficar disponível publicamente

### ISSUE THREAD

**Issue by diogob003** [VictorHSCosta/Projeto-Final#8]
O arquivo [.env](/VictorHSCosta/Projeto-Final/blob/main/.env) é onde são guardadas configuações **CONFIDENCIAIS**, chaves, senhas, tokens de autenticação... e portanto não deve ser enviado ao GitHub.

Regressão introduzina pelo commit: 1a5fa662679bfe9f6d43fdfcc121d77b3ae3efb7

**Comment by VictorHSCosta** [comment]
Eu ja coloquei novamente o .env no arquivo .gitignor
